/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mynanojava_MyNanoJava */

#ifndef _Included_org_mynanojava_MyNanoJava
#define _Included_org_mynanojava_MyNanoJava
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_mynanojava_MyNanoJava
 * Method:    license
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mynanojava_MyNanoJava_license
  (JNIEnv *, jobject);

/*
 * Class:     org_mynanojava_MyNanoJava
 * Method:    nano_add_sub
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mynanojava_MyNanoJava_nano_1add_1sub
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     org_mynanojava_MyNanoJava
 * Method:    nano_create_block
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_mynanojava_MyNanoJava_nano_1create_1block
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
