/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mynanojava_bitcoin_Util */

#ifndef _Included_org_mynanojava_bitcoin_Util
#define _Included_org_mynanojava_bitcoin_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mynanojava_bitcoin_Util
 * Method:    generateMasterKey
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mynanojava_bitcoin_Util_generateMasterKey
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
